import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
shell = "/opt/homebrew/bin/fish"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 20

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[mouse]
hide_when_typing = false

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
decorations = "Buttonless"
title = "Alacritty"
dynamic_title = true
opacity = 1
