format = """
$custom\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$dotnet\
$golang\
$java\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$character"""

[custom.bash]
command = 'echo bash'
when = ''' test "$SHELL" = "/bin/bash" '''
disabled = false
