#!/bin/sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Setting up the general bar appearance and default values
sketchybar --bar     height=42                                         \
                     position=top                                      \
                     sticky=on                                         \
                     color=$BASE                                \
                     border_width=2 \
                     border_color=$LAVENDER \
                     y_offset=-2 \
                     margin=-2 \
                     notch_width=170 \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     padding_right=$PADDINGS                           \
                     padding_left=$PADDINGS                            \
                     background.height=38                              \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=9                  \
                     popup.background.border_color=$PEACH \
                     popup.background.color=$BASE    \
                     popup.background.shadow.drawing=on

# Left
source "$ITEM_DIR/spaces.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/disk.sh"
# source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/memory.sh"

# Right of notch
source "$ITEM_DIR/alias.sh"

# Left of notch
# source "$ITEM_DIR/todo.sh"
source "$ITEM_DIR/utc.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."

# Force triggers
sleep 1 && sketchybar --trigger refresh_spaces
sleep 1 && sketchybar --trigger refresh_focus
