import * as Icons from "./components/icons.jsx";

export const apps = {
  "1Password 7": Icons.OnePassword,
  "App Store": Icons.AppStore,
  "Brave Browser": Icons.BraveBrowser,
  Calendar: Icons.Calendar,
  Code: Icons.Code,
  "Code - Insiders": Icons.Code,
  VSCodium: Icons.VSCodium,
  Default: Icons.Default,
  Discord: Icons.Discord,
  "Discord Canary": Icons.Discord,
  "Discord PTB": Icons.Discord,
  Dropbox: Icons.Dropbox,
  "Microsoft Excel": Icons.MicrosoftExcel,
  FaceTime: Icons.FaceTime,
  Finder: Icons.Finder,
  "Firefox Developer Edition": Icons.FirefoxDeveloperEdition,
  "Firefox Nightly": Icons.FirefoxDeveloperEdition,
  Firefox: Icons.Firefox,
  "GitHub Desktop": Icons.GitHub,
  "Google Chrome": Icons.GoogleChrome,
  "Google Chrome Canary": Icons.GoogleChrome,
  "Grammarly Editor": Icons.Grammarly,
  iTerm2: Icons.Terminal,
  kitty: Icons.Terminal,
  Messages: Icons.Messages,
  "Microsoft Edge": Icons.MicrosoftEdge,
  "Microsoft To Do": Icons.Things,
  Music: Icons.Music,
  Neovide: Icons.Vim,
  Notes: Icons.Notes,
  Notion: Icons.Notion,
  Obsidian: Icons.Obsidian,
  Numbers: Icons.Numbers,
  Pages: Icons.Pages,
  Podcasts: Icons.Podcasts,
  Preview: Icons.PDF,
  "Microsoft PowerPoint": Icons.MicrosoftPowerPoint,
  Reminders: Icons.Reminders,
  Safari: Icons.Safari,
  "Safari Technology Preview": Icons.Safari,
  Signal: Icons.Signal,
  Skype: Icons.Skype,
  Slack: Icons.Slack,
  Spotify: Icons.Spotify,
  Spotlight: Icons.Spotlight,
  "Sublime Text": Icons.SublimeText,
  Telegram: Icons.Telegram,
  Terminal: Icons.Terminal,
  Things: Icons.Things,
  Twitter: Icons.Twitter,
  Vim: Icons.Vim,
  VimR: Icons.Vim,
  VLC: Icons.VLC,
  "VMware Fusion": Icons.VMwareFusion,
  WhatsApp: Icons.WhatsApp,
  "Microsoft Word": Icons.MicrosoftWord,
  Zotero: Icons.Zotero,
  "zoom.us": Icons.Zoom,
  WebStorm: Icons.WebStorm,
  "IntelliJ IDEA": Icons.Idea,
  Thunderbird: Icons.Thunderbird,
  Notability: Icons.Notability,
  "Color Picker": Icons.ColorPicker,
  Xcode: Icons.Xcode,
  "Tor Browser": Icons.TorBrowser,
  "System Preferences": Icons.Gear,
  Trello: Icons.Trello,
  "Final Cut Pro": Icons.FinalCutPro,
  Matlab: Icons.Matlab,
  "Parallels Desktop": Icons.Parallels,
};
