#!/usr/bin/env python3
# vim: ft=python

import re
import subprocess
from typing import Set

import click


def get_branches():
    text = subprocess.check_output(["git", "branch", "--sort=-committerdate"])
    text = text.decode("utf-8")
    return list(filter(None, text.split("\n")))


def clean(branch: str):
    return re.sub(r"[^a-zA-Z0-9\-_/]+", "", branch)


def delete_branches(branches: Set[str]):
    for b in branches:
        subprocess.call(["git", "branch", "-D", b])


def main():
    branches = get_branches()
    res = click.edit("\n".join(branches), require_save=True)
    if res is None:
        return

    new_branches = set(map(lambda x: clean(x), filter(None, res.split("\n"))))
    old_branches = set(map(lambda x: clean(x), filter(None, branches)))

    deleted = old_branches - new_branches
    if not deleted:
        return

    click.secho("Deleting branches", fg="red")
    for d in deleted:
        if not d:
            continue
        click.secho(f"- {d}", fg="red")
    print()

    conf = click.confirm("Are you sure you want to delete them?")
    if not conf:
        return

    delete_branches(deleted)
    click.secho("Branches deleted", fg="green")


main()
