#!/usr/bin/env bash
# vim: set ft=bash

REPO_PATH=~/personal/dotfiles  
  
pushd . > /dev/null

cd "$REPO_PATH" || exit
  
git remote update &> /dev/null  
COMMITS_BEHIND=$(git rev-list --count HEAD...@{u} 2> /dev/null)  
  
popd > /dev/null || exit
  
if [ ! "$COMMITS_BEHIND" -eq "0" ]; then
    echo -e "\033[1m\033[91mYour dotfiles are outdated! Please, pull the remote changes.\033[0m"
fi  
