#!/usr/bin/env bash
# vim: set ft=bash

cache_file=~/.dotfiles_updates_cache  
repo_path=~/personal/dotfiles  
today_date=$(date '+%Y-%m-%d %H')  

check() {
    echo $today_date > $cache_file  
    pushd . > /dev/null
    cd "$repo_path" || exit
    git remote update &> /dev/null  
    COMMITS_BEHIND=$(git rev-list --count HEAD...@{u} 2> /dev/null)  
    popd > /dev/null || exit
    if [ ! "$COMMITS_BEHIND" -eq "0" ]; then
        echo -e "\033[1m\033[91mYour dotfiles are outdated! Please, pull the remote changes.\033[0m" >> $cache_file
    fi
}

check_or_cache() {  
    if [[ "$1" == "--help" ]] || [[ "$1" == "help" ]]; then
        echo -e "Usage: dotfiles-update-checker [OPTIONS]\n"
        echo "Options:"
        echo " --force/-f    Skip the hourly cache"
        return
    fi

    # Check for --force
    force=0
    if [[ "$1" == "--force" ]] || [[ "$1" == "-f" ]]; then
        force=1
    fi

    # Check if should run without cache
    if [[ "$force" -eq 1 ]] || [[ ! -e "$cache_file" ]] || [[ "$(head -n 1 "$cache_file")" != "$today_date" ]]; then
        check
    fi 

    # If any output, print
    if [[ "$(sed -n '2p' $cache_file)" ]]; then
        sed -n '2p' "$cache_file"  
    fi
}

check_or_cache $1
